name: Testes de CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  check-typescript:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:18-alpine
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        ports:
          - ${{ secrets.POSTGRES_HOST_PORT }}:5432
      redis:
        image: redis:8.4.0-alpine
        ports:
          - ${{ secrets.REDIS_HOST_PORT }}:6379
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      REDIS_HOST: ${{ secrets.REDIS_HOST }}
      REDIS_DB: ${{ secrets.REDIS_DB }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: yarn
      - run: yarn prisma generate
      - run: yarn tsc
  check-unit-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:18-alpine
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        ports:
          - ${{ secrets.POSTGRES_HOST_PORT }}:5432
      redis:
        image: redis:8.4.0-alpine
        ports:
          - ${{ secrets.REDIS_HOST_PORT }}:6379
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      REDIS_HOST: ${{ secrets.REDIS_HOST }}
      REDIS_DB: ${{ secrets.REDIS_DB }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: yarn
      - run: yarn prisma generate
      - run: yarn test:unit
  check-linting:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:18-alpine
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        ports:
          - ${{ secrets.POSTGRES_HOST_PORT }}:5432
      redis:
        image: redis:8.4.0-alpine
        ports:
          - ${{ secrets.REDIS_HOST_PORT }}:6379
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      REDIS_HOST: ${{ secrets.REDIS_HOST }}
      REDIS_DB: ${{ secrets.REDIS_DB }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: yarn
      - run: yarn prisma generate
      - run: yarn lint
